### ISSUE TITLE
macOS: client v0.15.1 still go in App Nap mode

### ISSUE THREAD

**Issue by fernetmatt** [bitcoin/bitcoin#11896]
Currently the Bitcoin Core client, v0.15.1 (64-bit) on macOS Sierra 10.12.6 still go in App Nap mode after being hidden behind other applications or docked in the macOS dock bar. Keeping the app in foreground will obviously avoid the App Nap mode. At the moment it is even impossible to disable per-app Nap Mode via the Get Info dialog because there is no option to do that with the Bitcoin client app.

The App Nap issue was already addressed and solved in few previous ticket (#3182, #5041, #5804).

I don't really know how App Nap can interfere with the client performance, at the moment i'm syncing the whole blockchain and it's taking a lot.

![screen shot 2017-12-14 at 10 59 56](https://user-images.githubusercontent.com/385030/33986928-6cd532a2-e0bf-11e7-8723-1850cfa56142.png)

**Comment by fanquake** [comment]
From a quick search, it looks like Apple has removed the ability to disable AppNap completely via plist, I can no longer find mention of "LSAppNapIsDisabled" in any documentation. 

Not sure if we want to revisit something like #5804. More info here: https://developer.apple.com/library/content/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/AppNap.html

**Comment by fernetmatt** [comment]
Why not temporary enable the "Prevent App Nap" option in App Info? App Nap is causing major slow down to the blockchain sync, when in nap mode the app progress like 0.5%/day, when it's in foreground the progress improve dramatically.

![screen shot 2017-12-16 at 16 20 56](https://user-images.githubusercontent.com/385030/34071890-19e80d42-e27e-11e7-9051-dfb36d70e61e.png)

**Comment by fanquake** [comment]
Should be resolved by #12783.

**Comment by Sjors** [comment]
It's indeed solved. A related problem remains, which is that MacBooks auto suspend by default, even when plugged in. That can be "fixed" with better instructions though: #16125.
