### ISSUE TITLE
mac: make check failure on macOS 10.14

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#14349]
Using `brew` installed Qt 5.11.2.
```
./autogen.sh
./configure
make check -j8
.....
Running tests: coinselector_tests from wallet/test/coinselector_tests.cpp
../build-aux/test-driver: line 107: 74758 Abort trap: 6           "$@" > $log_file 2>&1
FAIL: qt/test/test_bitcoin-qt
```

```
********* Finished testing of CompatTests *********
********* Start testing of WalletTests *********
Config: Using QtTest library 5.11.2, Qt 5.11.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 9.1.0 (clang-902.0.39.2) (Apple))
PASS   : WalletTests::initTestCase()
QDEBUG : WalletTests::walletTests() TransactionTablePriv::refreshWallet
QWARN  : WalletTests::walletTests() This plugin does not support propagateSizeHints()

=== Received signal at function time: 701ms, total time: 701ms, dumping stack ===
(lldb) process attach --pid 74758
Process 74758 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fff657b0e72 libsystem_kernel.dylib`__wait4_nocancel + 10
libsystem_kernel.dylib`__wait4_nocancel:
->  0x7fff657b0e72 <+10>: jae    0x7fff657b0e7c            ; <+20>
    0x7fff657b0e74 <+12>: movq   %rax, %rdi
    0x7fff657b0e77 <+15>: jmp    0x7fff657a8e67            ; cerror_nocancel
    0x7fff657b0e7c <+20>: retq   
Target 0: (test_bitcoin-qt) stopped.

Executable module set to "/Users/michael/github/bitcoin/src/./qt/test/test_bitcoin-qt".
Architecture set to: x86_64h-apple-macosx.
(lldb) bt all
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007fff657b0e72 libsystem_kernel.dylib`__wait4_nocancel + 10
    frame #1: 0x00007fff65737aea libsystem_c.dylib`system + 452
    frame #2: 0x000000010b0dbd25 QtTest`___lldb_unnamed_symbol21$$QtTest + 325
    frame #3: 0x000000010b0dbb8d QtTest`___lldb_unnamed_symbol20$$QtTest + 205
    frame #4: 0x00007fff65859b3d libsystem_platform.dylib`_sigtramp + 29
    frame #5: 0x00007fff64593a1e libobjc.A.dylib`objc_msgSend + 30
    frame #6: 0x000000010ef5713b libqmacstyle.dylib`___lldb_unnamed_symbol56$$libqmacstyle.dylib + 235
    frame #7: 0x000000010ef60942 libqmacstyle.dylib`___lldb_unnamed_symbol89$$libqmacstyle.dylib + 18802
    frame #8: 0x000000010b2fe13b QtWidgets`QCommonStyle::drawControl(QStyle::ControlElement, QStyleOption const*, QPainter*, QWidget const*) const + 891
    frame #9: 0x000000010ef5cd28 libqmacstyle.dylib`___lldb_unnamed_symbol89$$libqmacstyle.dylib + 3416
    frame #10: 0x000000010b412b65 QtWidgets`QPushButton::paintEvent(QPaintEvent*) + 117
    frame #11: 0x000000010b2ba5ec QtWidgets`QWidget::event(QEvent*) + 1116
    frame #12: 0x000000010b2802fd QtWidgets`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
    frame #13: 0x000000010b281727 QtWidgets`QApplication::notify(QObject*, QEvent*) + 583
    frame #14: 0x000000010ad07a64 QtCore`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
    frame #15: 0x000000010b2b3082 QtWidgets`QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 3138
    frame #16: 0x000000010b2b3801 QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1121
    frame #17: 0x000000010b2b369d QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 765
    frame #18: 0x000000010b2b31ea QtWidgets`QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 3498
    frame #19: 0x000000010b2b3801 QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1121
    frame #20: 0x000000010b2b31ea QtWidgets`QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 3498
    frame #21: 0x000000010b28d55a QtWidgets`___lldb_unnamed_symbol97$$QtWidgets + 4586
    frame #22: 0x000000010b28c0e7 QtWidgets`___lldb_unnamed_symbol95$$QtWidgets + 279
    frame #23: 0x000000010b2dbe3a QtWidgets`___lldb_unnamed_symbol487$$QtWidgets + 314
    frame #24: 0x000000010b2d9519 QtWidgets`___lldb_unnamed_symbol473$$QtWidgets + 1049
    frame #25: 0x000000010b2802fd QtWidgets`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
    frame #26: 0x000000010b281727 QtWidgets`QApplication::notify(QObject*, QEvent*) + 583
    frame #27: 0x000000010ad07a64 QtCore`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
    frame #28: 0x000000010b84ef01 QtGui`QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) + 321
    frame #29: 0x000000010b832c0b QtGui`QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 219
    frame #30: 0x000000010b82de27 QtGui`QWindowSystemInterface::flushWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 599
    frame #31: 0x000000010b83f7d2 QtGui`QPlatformWindow::setVisible(bool) + 114
    frame #32: 0x000000010b8559b9 QtGui`QWindowPrivate::setVisible(bool) + 1081
    frame #33: 0x000000010b2b71ea QtWidgets`QWidgetPrivate::show_sys() + 890
    frame #34: 0x000000010b2b9329 QtWidgets`QWidgetPrivate::show_helper() + 409
    frame #35: 0x000000010b2b9fc3 QtWidgets`QWidget::setVisible(bool) + 963
    frame #36: 0x000000010b482d5d QtWidgets`QDialog::setVisible(bool) + 125
    frame #37: 0x000000010b482483 QtWidgets`QDialog::exec() + 243
    frame #38: 0x000000010a08e30e test_bitcoin-qt`SendCoinsDialog::on_sendButton_clicked() [inlined] SendConfirmationDialog::exec(this=0x000000010a60dfe8) at sendcoinsdialog.cpp:907 [opt]
    frame #39: 0x000000010a08e2e9 test_bitcoin-qt`SendCoinsDialog::on_sendButton_clicked(this=0x00007ffee5bf3a00) at sendcoinsdialog.cpp:363 [opt]
    frame #40: 0x000000010ad11c7c QtCore`QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const + 1308
    frame #41: 0x000000010ad11209 QtCore`QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) + 2009
    frame #42: 0x000000010a03c53b test_bitcoin-qt`(anonymous namespace)::SendCoins(CWallet&, SendCoinsDialog&, boost::variant<CNoDestination, CKeyID, CScriptID, WitnessV0ScriptHash, WitnessV0KeyHash, WitnessUnknown> const&, long long, bool) [inlined] QMetaObject::invokeMethod(obj=<unavailable>, member=<unavailable>, val0=<unavailable>) at qobjectdefs.h:460 [opt]
    frame #43: 0x000000010a03c438 test_bitcoin-qt`(anonymous namespace)::SendCoins(wallet=0x00007f839700ae18, sendCoinsDialog=<unavailable>, address=<unavailable>, amount=<unavailable>, rbf=false) at wallettests.cpp:72 [opt]
    frame #44: 0x000000010a039f15 test_bitcoin-qt`(anonymous namespace)::TestGUI() at wallettests.cpp:167 [opt]
    frame #45: 0x000000010ad11c7c QtCore`QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const + 1308
    frame #46: 0x000000010b0d9b24 QtTest`___lldb_unnamed_symbol12$$QtTest + 1092
    frame #47: 0x000000010b0da80c QtTest`___lldb_unnamed_symbol14$$QtTest + 812
    frame #48: 0x000000010b0db757 QtTest`___lldb_unnamed_symbol18$$QtTest + 1015
    frame #49: 0x000000010b0dc35a QtTest`QTest::qRun() + 282
    frame #50: 0x000000010b0dbf94 QtTest`QTest::qExec(QObject*, int, char**) + 20
    frame #51: 0x000000010a019b49 test_bitcoin-qt`main(argc=<unavailable>, argv=<unavailable>) at test_main.cpp:93 [opt]
    frame #52: 0x00007fff65670085 libdyld.dylib`start + 1
  thread #2
    frame #0: 0x00007fff657aa5be libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fff65861641 libsystem_pthread.dylib`_pthread_wqthread + 446
    frame #2: 0x00007fff65861415 libsystem_pthread.dylib`start_wqthread + 13
  thread #3
    frame #0: 0x00007fff657aa5be libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fff65861721 libsystem_pthread.dylib`_pthread_wqthread + 670
    frame #2: 0x00007fff65861415 libsystem_pthread.dylib`start_wqthread + 13
  thread #4, name = 'Qt bearer thread'
    frame #0: 0x00007fff657b0b8e libsystem_kernel.dylib`poll + 10
    frame #1: 0x000000010ad5bc5a QtCore`qt_safe_poll(pollfd*, unsigned int, timespec const*) + 90
    frame #2: 0x000000010ad5d6c9 QtCore`QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 873
    frame #3: 0x000000010ad02ede QtCore`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 430
    frame #4: 0x000000010ab4726c QtCore`QThread::exec() + 140
    frame #5: 0x000000010ab5075e QtCore`___lldb_unnamed_symbol310$$QtCore + 350
    frame #6: 0x00007fff6586233d libsystem_pthread.dylib`_pthread_body + 126
    frame #7: 0x00007fff658652a7 libsystem_pthread.dylib`_pthread_start + 70
    frame #8: 0x00007fff65861425 libsystem_pthread.dylib`thread_start + 13
  thread #5, name = 'QThread'
    frame #0: 0x00007fff657ac1b2 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff658655cb libsystem_pthread.dylib`_pthread_cond_wait + 724
    frame #2: 0x000000010ab52038 QtCore`___lldb_unnamed_symbol320$$QtCore + 296
    frame #3: 0x000000010ab51d8b QtCore`___lldb_unnamed_symbol319$$QtCore + 43
    frame #4: 0x000000010ab51d01 QtCore`QWaitCondition::wait(QMutex*, unsigned long) + 97
    frame #5: 0x000000010b0e1385 QtTest`___lldb_unnamed_symbol36$$QtTest + 69
    frame #6: 0x000000010ab5075e QtCore`___lldb_unnamed_symbol310$$QtCore + 350
    frame #7: 0x00007fff6586233d libsystem_pthread.dylib`_pthread_body + 126
    frame #8: 0x00007fff658652a7 libsystem_pthread.dylib`_pthread_start + 70
    frame #9: 0x00007fff65861425 libsystem_pthread.dylib`thread_start + 13
  thread #6
    frame #0: 0x00007fff657ac1b2 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff658655cb libsystem_pthread.dylib`_pthread_cond_wait + 724
    frame #2: 0x000000010a2f60d8 test_bitcoin-qt`boost::condition_variable::do_wait_until(this=0x00007ffee5bf3f18, m=0x0000700001aa6e60, timeout=0x0000700001aa6e70) at condition_variable.hpp:128 [opt]
    frame #3: 0x000000010a40a872 test_bitcoin-qt`CScheduler::serviceQueue() [inlined] boost::cv_status boost::condition_variable::wait_until<boost::chrono::duration<long long, boost::ratio<1l, 1000000000l> > >(this=<unavailable>, lock=0x00007ffee5bf3f88) at condition_variable_fwd.hpp:252 [opt]
    frame #4: 0x000000010a40a83e test_bitcoin-qt`CScheduler::serviceQueue(this=0x00007ffee5bf3f00) at scheduler.cpp:67 [opt]
    frame #5: 0x000000010aa6a5ea libboost_thread-mt.dylib`boost::(anonymous namespace)::thread_proxy(void*) + 154
    frame #6: 0x00007fff6586233d libsystem_pthread.dylib`_pthread_body + 126
    frame #7: 0x00007fff658652a7 libsystem_pthread.dylib`_pthread_start + 70
    frame #8: 0x00007fff65861425 libsystem_pthread.dylib`thread_start + 13
  thread #7, name = 'bitcoin-scriptch'
    frame #0: 0x00007fff657ac1b2 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff658655cb libsystem_pthread.dylib`_pthread_cond_wait + 724
    frame #2: 0x000000010a023e7f test_bitcoin-qt`boost::condition_variable::wait(this=0x000000010a624618, m=0x0000700001b29e70) at condition_variable.hpp:85 [opt]
    frame #3: 0x000000010a299e25 test_bitcoin-qt`CCheckQueue<CScriptCheck>::Loop(this=0x000000010a6245d8, fMaster=false) at checkqueue.h:99 [opt]
    frame #4: 0x000000010aa6a5ea libboost_thread-mt.dylib`boost::(anonymous namespace)::thread_proxy(void*) + 154
    frame #5: 0x00007fff6586233d libsystem_pthread.dylib`_pthread_body + 126
    frame #6: 0x00007fff658652a7 libsystem_pthread.dylib`_pthread_start + 70
    frame #7: 0x00007fff65861425 libsystem_pthread.dylib`thread_start + 13
  thread #8, name = 'bitcoin-scriptch'
    frame #0: 0x00007fff657ac1b2 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff658655cb libsystem_pthread.dylib`_pthread_cond_wait + 724
    frame #2: 0x000000010a023e7f test_bitcoin-qt`boost::condition_variable::wait(this=0x000000010a624618, m=0x0000700001bace70) at condition_variable.hpp:85 [opt]
    frame #3: 0x000000010a299e25 test_bitcoin-qt`CCheckQueue<CScriptCheck>::Loop(this=0x000000010a6245d8, fMaster=false) at checkqueue.h:99 [opt]
    frame #4: 0x000000010aa6a5ea libboost_thread-mt.dylib`boost::(anonymous namespace)::thread_proxy(void*) + 154
    frame #5: 0x00007fff6586233d libsystem_pthread.dylib`_pthread_body + 126
    frame #6: 0x00007fff658652a7 libsystem_pthread.dylib`_pthread_start + 70
    frame #7: 0x00007fff65861425 libsystem_pthread.dylib`thread_start + 13
  thread #9
    frame #0: 0x00007fff657aa5be libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fff65861641 libsystem_pthread.dylib`_pthread_wqthread + 446
    frame #2: 0x00007fff65861415 libsystem_pthread.dylib`start_wqthread + 13
  thread #10
    frame #0: 0x0000000000000000
(lldb) quit
=== End of stack trace ===
QFATAL : WalletTests::walletTests() Received signal 11
         Function time: 701ms Total time: 701ms
FAIL!  : WalletTests::walletTests() Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 1 passed, 1 failed, 0 skipped, 0 blacklisted, 3392ms
********* Finished testing of WalletTests *********
FAIL qt/test/test_bitcoin-qt (exit status: 134)
```

**Comment by jonasschnelli** [comment]
Can confirm:

```shell
FAIL: qt/test/test_bitcoin-qt
============================================================================
Testsuite summary for Bitcoin Core 0.17.99
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/bitcoin/bitcoin/issues
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
users-Mac:bitcoin user$ cat src/test-suite.log 
==============================================
   Bitcoin Core 0.17.99: src/test-suite.log
==============================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: qt/test/test_bitcoin-qt
=============================

********* Start testing of URITests *********
Config: Using QtTest library 5.11.2, Qt 5.11.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 10.0.0 (clang-1000.10.43.1) (Apple))
PASS   : URITests::initTestCase()
PASS   : URITests::uriTests()
PASS   : URITests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 3ms
********* Finished testing of URITests *********
********* Start testing of PaymentServerTests *********
Config: Using QtTest library 5.11.2, Qt 5.11.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 10.0.0 (clang-1000.10.43.1) (Apple))
PASS   : PaymentServerTests::initTestCase()
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::initNetManager: No active proxy server found.
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Secure payment request from  "testmerchant.org"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: Payment request: certificate expired or not yet active:  QSslCertificate("3", "03", "LxHILx+N3qwVoAcCmQ5cyw==", (), ("Expired Test Merchant"), QMap(), QDateTime(2013-02-23 21:26:43.000 UTC Qt::TimeSpec(UTC)), QDateTime(2013-02-24 21:26:43.000 UTC Qt::TimeSpec(UTC)))
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Insecure payment request to  "1EcqLEpyu3zY7T5QU7RLrHEQH134KeGPXR"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: Payment request: certificate expired or not yet active:  QSslCertificate("3", "03", "LxHILx+N3qwVoAcCmQ5cyw==", (), ("Expired Test Merchant"), QMap(), QDateTime(2013-02-23 21:26:43.000 UTC Qt::TimeSpec(UTC)), QDateTime(2013-02-24 21:26:43.000 UTC Qt::TimeSpec(UTC)))
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Secure payment request from  "testmerchant8.org"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: Payment request: certificate expired or not yet active:  QSslCertificate("3", "06", "MiZaQ+g9lSHZGuHWkXZG+g==", (), ("Payment Request Intermediate 5"), QMap(), QDateTime(2013-02-23 22:59:51.000 UTC Qt::TimeSpec(UTC)), QDateTime(2013-02-24 22:59:51.000 UTC Qt::TimeSpec(UTC)))
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Insecure payment request to  "1EcqLEpyu3zY7T5QU7RLrHEQH134KeGPXR"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: Payment request: certificate expired or not yet active:  QSslCertificate("3", "06", "MiZaQ+g9lSHZGuHWkXZG+g==", (), ("Payment Request Intermediate 5"), QMap(), QDateTime(2013-02-23 22:59:51.000 UTC Qt::TimeSpec(UTC)), QDateTime(2013-02-24 22:59:51.000 UTC Qt::TimeSpec(UTC)))
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: SSL error:  certificate signature failure
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Insecure payment request to  "1EcqLEpyu3zY7T5QU7RLrHEQH134KeGPXR"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: SSL error:  certificate signature failure
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: SSL error:  unable to get local issuer certificate
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Insecure payment request to  "1EcqLEpyu3zY7T5QU7RLrHEQH134KeGPXR"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: SSL error:  unable to get local issuer certificate
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifyNetwork: Payment request network \"test\" doesn't match client network \"main\"."
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifyExpired: Payment request expired \"1970-01-01T00:00:01Z\"."
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifyExpired: Payment request expired \"1900-01-8096T08:29:52Z\"."
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifySize: Payment request too large (50001 bytes, allowed 50000 bytes)."
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifyAmount: Payment request amount out of allowed range (2100000100000000, allowed 0 - 2100000000000000)."
PASS   : PaymentServerTests::paymentServerTests()
PASS   : PaymentServerTests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 602ms
********* Finished testing of PaymentServerTests *********
********* Start testing of RPCNestedTests *********
Config: Using QtTest library 5.11.2, Qt 5.11.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 10.0.0 (clang-1000.10.43.1) (Apple))
PASS   : RPCNestedTests::initTestCase()
PASS   : RPCNestedTests::rpcNestedTests()
PASS   : RPCNestedTests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 105ms
********* Finished testing of RPCNestedTests *********
********* Start testing of CompatTests *********
Config: Using QtTest library 5.11.2, Qt 5.11.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 10.0.0 (clang-1000.10.43.1) (Apple))
PASS   : CompatTests::initTestCase()
PASS   : CompatTests::bswapTests()
PASS   : CompatTests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 0ms
********* Finished testing of CompatTests *********
********* Start testing of WalletTests *********
Config: Using QtTest library 5.11.2, Qt 5.11.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 10.0.0 (clang-1000.10.43.1) (Apple))
PASS   : WalletTests::initTestCase()
QDEBUG : WalletTests::walletTests() TransactionTablePriv::refreshWallet
QWARN  : WalletTests::walletTests() This plugin does not support propagateSizeHints()
QFATAL : WalletTests::walletTests() Received signal 11
         Function time: 911ms Total time: 911ms
FAIL!  : WalletTests::walletTests() Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 1 passed, 1 failed, 0 skipped, 0 blacklisted, 911ms
********* Finished testing of WalletTests *********
FAIL qt/test/test_bitcoin-qt (exit status: 134)
```

**Comment by fanquake** [comment]
This will be taken care of (even just in the interim) by something like #14011.

**Comment by fanquake** [comment]
Fixed by #14011.

**Comment by brentkearney** [comment]
I still get this error, on x64 with MacOS 10.14.3, qt stable 5.12.1.

```
$ brew info qt | head -n1
qt: stable 5.12.1 (bottled), HEAD [keg-only]
$ uname -a
Darwin f008.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

```
$ make check
Making check in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS check-local
FAIL: qt/test/test_bitcoin-qt
============================================================================
Testsuite summary for Bitcoin Core 0.17.99
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/bitcoin/bitcoin/issues
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

Promag's comment in [#14011](https://github.com/bitcoin/bitcoin/pull/14011#issuecomment-431380010) to specify `-platform minimal` did not work for me:

```
$ src/qt/test/test_bitcoin-qt -platform minimal
-bash: src/qt/test/test_bitcoin-qt: Permission denied
$ sudo src/qt/test/test_bitcoin-qt -platform minimal
Password:
sudo: unable to execute src/qt/test/test_bitcoin-qt: Permission denied
```

I also get "permission denied" when trying to launch the binary from 
https://bitcoincore.org/bin/bitcoin-core-0.17.1/bitcoin-0.17.1-osx.dmg. Attempting to run it directly from the disk image produces the error message, "You can't open the application "Bitcoin Core" because it is not supported on this type of Mac."

**Comment by ryanofsky** [comment]
"Permission denied" from bash usually just means that the binary is not executable.

You might want to try checking permissions with `stat src/qt/test/test_bitcoin-qt` or `ls -l src/qt/test/test_bitcoin-qt` and maybe changing them with `chmod +x src/qt/test/test_bitcoin-qt`

**Comment by brentkearney** [comment]
Normally it does; however, in this case it is some indication of incompatibility with the hardware platform. If I try to run the binary, I get a pop-up message saying, "You can't open the application because it is not supported on this type of Mac."

The file permission was "-rwx--x--x  "; setting it to 755 made no difference.
