### ISSUE TITLE
v0.19.0rc1 GUI repeatedly not responding

### ISSUE THREAD

**Issue by mmortal03** [bitcoin/bitcoin#17112]
The v0.19.0rc1 Qt GUI repeatedly stops responding, i.e. getting "(not responding)" on the GUI title bar, and the GUI window whites out when clicking, then after a few seconds it will come back for a bit, then go back to not responding again. The blockchain synchronization still makes progress in spite of this happening. It seems to be happening during synchronizing, but I believe I also saw it happen at the initial loading window, and while "reading from disk". 

I'm running Windows 10 64-bit, v1803, on an older, low-end, AMD E-350 netbook, 6 GB RAM. I've used this machine as a node for a long time. The blockchain data is stored externally on a USB 3.0 connected hard disk drive, using a soft link (symbolic link) to the "C:\Users\Username\AppData\Roaming\Bitcoin" directory.  I doubt this particular part is the cause of the problem, as I've been running this configuration, unchanged, for many past versions.

I made sure to go back to v0.18.1 to be sure it's not caused by any sort of recent system malfunction, and it's not, as v0.18.1 continues to run just fine.

I downloaded from: https://bitcoin.org/bin/bitcoin-core-0.19.0/test.rc1/bitcoin-0.19.0rc1-win64-setup.exe

Here is my bitcoin.conf:
rpcport=set
server=1
listen=1
daemon=1
txindex=1
rpcuser=set
rpcpassword=set
maxuploadtarget=36
disablewallet=1
listenonion=0

**Comment by promag** [comment]
Have you tried disabling txindex?

**Comment by MarcoFalke** [comment]
> USB 3.0 connected hard disk drive

As a side note, this is a common cause of chainstate corruption.


Could you check the debug.log when this happens? The cause might be slow disk access, but it might be good to confirm.

You can find the debug.log in your [data dir](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location).

**Comment by mmortal03** [comment]
> Have you tried disabling txindex?

Just tried it -- didn't help. I've also just tested with *all* configuration settings in bitcoin.conf commented out except for disablewallet=1, and it's still doing repeated not responding when clicking through the GUI. It seems like it reproducibly starts to happen once it connects to peers. This should rule out any special settings other than disablewallet.

> As a side note, this is a common cause of chainstate corruption.

Yeah, I know it's not recommended. To keep it as safe as possible I make regular blockchain backups, never disconnect the drive or touch the USB cord while the machine is running, the external drive is a dual drive RAID1 enclosure, and everything is connected to a UPS. It sits in a closet on a shelf out of the way. I don't have another machine that's convenient to dedicate to it. I've been running it like this for almost three years, and haven't run into any chainstate corruption that I'm aware of.

> The cause might be slow disk access, but it might be good to confirm.

I just did a drive speed test, getting 72 MB/s average read, 66 MB/s average write. Keep in mind, the problem isn't happening on 0.18.1, with the same hardware.

> Could you check the debug.log when this happens? 

I don't see anything obvious. I'm getting warnings about '50 of last 100 blocks have unexpected version', but that is happening in both 0.18.1 (where the not responding isn't happening) and 0.19.0rc1. Take a look at it here: https://pastebin.com/4JAyBGaK

**Comment by MarcoFalke** [comment]
Hmm, I don't know any tools on Windows that could help debug this freeze.

**Comment by minblock** [comment]
Same problem with Windows prior to 18.99 I would get block index errors.

**Comment by mmortal03** [comment]
> Hmm, I don't know any tools on Windows that could help debug this freeze.

Yeah, I recall running into a past issue on Windows and also wasn't able to debug it. I don't recall how it was resolved. The following is something using wine, but I've never tried it: https://stackoverflow.com/questions/39938253/how-to-properly-debug-a-cross-compiled-windows-code-on-linux/39942833

@minblock might be on the right track, in terms of tracking down the last potential build that doesn't freeze. I'm not set up to compile Bitcoin on this machine, but I can work toward that. I'll also work toward testing it on a more powerful machine.

**Comment by mmortal03** [comment]
Alright, I did some testing of nightlies, working my way backwards. 

I think the last build *before* the bug is this:
https://bitcoin.jonasschnelli.ch/build/1139

So, the buggy behavior begins here:
https://bitcoin.jonasschnelli.ch/build/1140

That would mean that one of the following is the source of the bug?
e06067387 Merge #16250: signrawtransactionwithkey: report error when missing redeemScript/witnessScript
4db2f8cf0 Merge #16153: Qt: Add antialiasing to traffic graph widget
c84349a14 Merge #16314: scripts and tools: Update copyright_header.py script
2f717fb5c Merge #15427: Add support for descriptors to utxoupdatepsbt
c6e42f1ca Merge #14193: validation: Add missing mempool locks
6c21a801f Merge #15538: wallet_bumpfee.py: Make sure coin selection produces change

**Comment by MarcoFalke** [comment]
Yeah, block activation in validation takes the mempool lock now. Is the gui polling something with that lock?

**Comment by promag** [comment]
It is:
https://github.com/bitcoin/bitcoin/blob/4765b91f507dc6f44122ed0062e74510577eea29/src/qt/clientmodel.cpp#L93-L100
which calls:
https://github.com/bitcoin/bitcoin/blob/4765b91f507dc6f44122ed0062e74510577eea29/src/txmempool.h#L677-L682

**Comment by promag** [comment]
Easy solution is to add an atomic int and keep it in sync with `mapTx.size()`?

**Comment by promag** [comment]
We should kill polling though.

**Comment by MarcoFalke** [comment]
Thanks, good find @promag

**Comment by promag** [comment]
On macos I also have the same "hanging". I guess this is only noticeable on windows because it shows "not responding".

**Comment by promag** [comment]
This snippet allows to identify moments where Qt event loop is busy with something else:
```diff
--- a/src/qt/bitcoin.cpp
+++ b/src/qt/bitcoin.cpp
@@ -40,6 +40,7 @@

 #include <QApplication>
 #include <QDebug>
+#include <QElapsedTimer>
 #include <QLibraryInfo>
 #include <QLocale>
 #include <QMessageBox>
@@ -585,6 +586,14 @@ int GuiMain(int argc, char* argv[])
 #if defined(Q_OS_WIN)
             WinShutdownMonitor::registerShutdownBlockReason(QObject::tr("%1 didn't yet exit safely...").arg(PACKAGE_NAME), (HWND)app.getMainWinId());
 #endif
+            QTimer t;
+            QElapsedTimer et;
+            QObject::connect(&t, &QTimer::timeout, [&]{
+                if (et.elapsed() > 20) printf("ain't no time.. %lld ms\n", et.elapsed());
+                et.restart();
+            });
+            t.start(16);
+
             app.exec();
             app.requestShutdown();
             app.exec();
```

**Comment by promag** [comment]
Also, looks like there's some huge hangs when switching tabs, especially "network traffic".

**Comment by mmortal03** [comment]
> Also, looks like there's some huge hangs when switching tabs, especially "network traffic".

Yep, clicking through the menus or tabs is how I've reproduced it.

I'd been wondering if there was an easy way to revert just that commit in git so I could compile it just for a quick test, but it looks like there isn't, so I'll wait. :)

**Comment by mmortal03** [comment]
Thanks, I can confirm that this fixes it in the latest nightly build. I'll look to test it in the next RC once that's released.

**Comment by mmortal03** [comment]
I just tested RC3. Looks fixed to me.

**Comment by promag** [comment]
Thanks @mmortal03, the regression has been fixed, you can now close this.

**Comment by merket** [comment]
> 
> 
> Thanks, I can confirm that this fixes it in the latest nightly build. I'll look to test it in the next RC once that's released.

Hello, I was having the same issue on 19.1 came across your post, learned about GUI causing the problem. I updated to 20.1 hoping that it was fixed but unfortunately still having the same problem which is seriously bothering me.

Could you please share with me step by step, how were you able to fix it?
Are you using an unreleased candidate version of Bitcoin perhaps?

**Comment by mmortal03** [comment]
> > Thanks, I can confirm that this fixes it in the latest nightly build. I'll look to test it in the next RC once that's released.
> 
> Hello, I was having the same issue on 19.1 came across your post, learned about GUI causing the problem. I updated to 20.1 hoping that it was fixed but unfortunately still having the same problem which is seriously bothering me.
> 
> Could you please share with me step by step, how were you able to fix it?
> Are you using an unreleased candidate version of Bitcoin perhaps?

This was fixed since 0.19.0rc3, and went into the final release of 0.19.0. If you've been seeing something similar since 0.19.1, then you've found a different issue.  I've run all the official releases since, and haven't seen the issue come back up, so there's got to be something particular about your situation. I'd suggest creating a new bug report and provide details about your system and configuration.

**Comment by sabotagebeats** [comment]
@mmortal03 having this issue on 20.1

**Comment by mmortal03** [comment]
> @mmortal03 having this issue on 20.1

It's probably a new bug. I've run practically every release since this was fixed, and haven't experienced the bug since then. I'm currently testing v0.21.0rc3 and don't see it. I wish I could help you, but I'm not a dev. You might try the RC for the upcoming release to see if you can still reproduce it: https://bitcoin.org/bin/bitcoin-core-0.21.0/test.rc3/
