### ISSUE TITLE
qa: Data race detected when running `mempool_expiry.py`

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19448]
https://cirrus-ci.com/task/4919890316361728?command=ci#L3486

Similar issues:
- #19211
- #19417

<details><summary>log excerpt</summary>
<p>

```
...
108/159 - mempool_expiry.py failed, Duration: 4 s
stdout:
2020-07-05T12:07:26.964000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20200705_114826/mempool_expiry_49
2020-07-05T12:07:29.624000Z TestFramework (INFO): Test default mempool expiry timeout of 336 hours.
2020-07-05T12:07:30.281000Z TestFramework (INFO): Broadcast child transaction after 7 days, 0:00:00 hours.
2020-07-05T12:07:30.641000Z TestFramework (INFO): Test parent tx not expired after 13 days, 23:59:55 hours.
2020-07-05T12:07:30.765000Z TestFramework (ERROR): Unexpected exception caught during testing
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 108, in _request
    return self._get_response()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 168, in _get_response
    http_response = self.__conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 117, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/mempool_expiry.py", line 91, in run_test
    self.test_transaction_expiry(DEFAULT_MEMPOOL_EXPIRY)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/mempool_expiry.py", line 77, in test_transaction_expiry
    node.sendtoaddress(node.getnewaddress(), 1.0)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 144, in __call__
    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 113, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 917, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2020-07-05T12:07:31.091000Z TestFramework (INFO): Stopping nodes
2020-07-05T12:07:31.092000Z TestFramework.node0 (ERROR): Unable to stop node.
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_node.py", line 319, in stop_node
    self.stop(wait=wait)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 144, in __call__
    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 107, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.8/http/client.py", line 1088, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent
stderr:
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/mempool_expiry.py", line 100, in <module>
    MempoolExpiryTest().main()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 140, in main
    exit_code = self.shutdown()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 264, in shutdown
    self.stop_nodes()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 525, in stop_nodes
    node.wait_until_stopped()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_node.py", line 362, in wait_until_stopped
    wait_until(self.is_node_stopped, timeout=timeout, timeout_factor=self.timeout_factor)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 241, in wait_until
    if predicate():
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_node.py", line 352, in is_node_stopped
    assert return_code == 0, self._node_msg(
AssertionError: [node 0] Node returned non-zero exit code (66) when stopping
...
mempool_expiry.py                     | ✖ Failed  | 4 s
ALL                                   | ✖ Failed  | 4500 s (accumulated) 
Runtime: 1142 s
==================
WARNING: ThreadSanitizer: data race (pid=37561)
  Write of size 1 at 0x7b84000208cc by thread T18 (mutexes: write M132362, write M132877):
    #0 memmove <null> (bitcoind+0x79de7)
    #1 __db_pitem <null> (bitcoind+0x880daf)
    #2 bool BerkeleyBatch::Write<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, CPubKey>, CKeyMetadata>(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, CPubKey> const&, CKeyMetadata const&, bool) <null> (bitcoind+0x592efe)
    #3 WalletBatch::WriteKeyMetadata(CKeyMetadata const&, CPubKey const&, bool) <null> (bitcoind+0x57e2d1)
    #4 WalletBatch::WriteKey(CPubKey const&, std::__1::vector<unsigned char, secure_allocator<unsigned char> > const&, CKeyMetadata const&) <null> (bitcoind+0x57e3ca)
    #5 LegacyScriptPubKeyMan::AddKeyPubKeyWithDB(WalletBatch&, CKey const&, CPubKey const&) <null> (bitcoind+0x5026af)
    #6 LegacyScriptPubKeyMan::GenerateNewKey(WalletBatch&, CHDChain&, bool) <null> (bitcoind+0x4fd0d8)
    #7 LegacyScriptPubKeyMan::TopUp(unsigned int) <null> (bitcoind+0x507948)
    #8 CWallet::GetNewDestination(OutputType, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, boost::variant<CNoDestination, PKHash, ScriptHash, WitnessV0ScriptHash, WitnessV0KeyHash, WitnessUnknown>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) <null> (bitcoind+0x551956)
    #9 getnewaddress(JSONRPCRequest const&) <null> (bitcoind+0x4a786a)
    #10 std::__1::__function::__func<CRPCCommand::CRPCCommand(char const*, char const*, UniValue (*)(JSONRPCRequest const&), std::initializer_list<char const*>)::'lambda'(JSONRPCRequest const&, UniValue&, bool), std::__1::allocator<CRPCCommand::CRPCCommand(char const*, char const*, UniValue (*)(JSONRPCRequest const&), std::initializer_list<char const*>)::'lambda'(JSONRPCRequest const&, UniValue&, bool)>, bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool&&) <null> (bitcoind+0x281bed)
    #11 std::__1::__function::__func<interfaces::(anonymous namespace)::WalletClientImpl::registerRpcs()::'lambda'(JSONRPCRequest const&, UniValue&, bool), std::__1::allocator<interfaces::(anonymous namespace)::WalletClientImpl::registerRpcs()::'lambda'(JSONRPCRequest const&, UniValue&, bool)>, bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool&&) <null> (bitcoind+0x43b86e)
    #12 std::__1::__function::__func<interfaces::(anonymous namespace)::RpcHandlerImpl::RpcHandlerImpl(CRPCCommand const&)::'lambda'(JSONRPCRequest const&, UniValue&, bool), std::__1::allocator<interfaces::(anonymous namespace)::RpcHandlerImpl::RpcHandlerImpl(CRPCCommand const&)::'lambda'(JSONRPCRequest const&, UniValue&, bool)>, bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool&&) <null> (bitcoind+0x147722)
    #13 CRPCTable::execute(JSONRPCRequest const&) const <null> (bitcoind+0x32afad)
    #14 std::__1::__function::__func<StartHTTPRPC(util::Ref const&)::$_0, std::__1::allocator<StartHTTPRPC(util::Ref const&)::$_0>, bool (HTTPRequest*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(HTTPRequest*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) <null> (bitcoind+0x400d2a)
    #15 HTTPWorkItem::operator()() <null> (bitcoind+0x40b072)
    #16 WorkQueue<HTTPClosure>::Run() <null> (bitcoind+0x40d175)
    #17 HTTPWorkQueueRun(WorkQueue<HTTPClosure>*, int) <null> (bitcoind+0x40731c)
    #18 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(WorkQueue<HTTPClosure>*, int), WorkQueue<HTTPClosure>*, int> >(void*) <null> (bitcoind+0x40dc38)
  Previous read of size 8 at 0x7b84000208c8 by thread T16:
    #0 pwrite <null> (bitcoind+0x7bc72)
    #1 __os_io <null> (bitcoind+0x806602)
    #2 BerkeleyBatch::Close() <null> (bitcoind+0x45955d)
    #3 CWallet::chainStateFlushed(CBlockLocator const&) <null> (bitcoind+0x53183c)
    #4 non-virtual thunk to CWallet::chainStateFlushed(CBlockLocator const&) <null> (bitcoind+0x5318ef)
    #5 interfaces::(anonymous namespace)::NotificationsProxy::ChainStateFlushed(CBlockLocator const&) <null> (bitcoind+0x146fb1)
    #6 std::__1::__function::__func<CMainSignals::ChainStateFlushed(CBlockLocator const&)::$_13, std::__1::allocator<CMainSignals::ChainStateFlushed(CBlockLocator const&)::$_13>, void ()>::operator()() <null> (bitcoind+0x3d1f4e)
    #7 SingleThreadedSchedulerClient::ProcessQueue() <null> (bitcoind+0x632816)
    #8 std::__1::__function::__func<std::__1::__bind<void (SingleThreadedSchedulerClient::*)(), SingleThreadedSchedulerClient*>, std::__1::allocator<std::__1::__bind<void (SingleThreadedSchedulerClient::*)(), SingleThreadedSchedulerClient*> >, void ()>::operator()() <null> (bitcoind+0x634736)
    #9 CScheduler::serviceQueue() <null> (bitcoind+0x6317e5)
    #10 boost::detail::thread_data<AppInitMain(util::Ref const&, NodeContext&)::$_4>::run() <null> (bitcoind+0x12354d)
    #11 boost::(anonymous namespace)::thread_proxy(void*) <null> (bitcoind+0x7a289e)
  Location is heap block of size 4184 at 0x7b8400020800 allocated by thread T18:
    #0 malloc <null> (bitcoind+0x6e8e4)
    #1 __os_malloc <null> (bitcoind+0x804b08)
    #2 bool BerkeleyBatch::Write<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, uint256>, CWalletTx>(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, uint256> const&, CWalletTx const&, bool) <null> (bitcoind+0x591e32)
    #3 WalletBatch::WriteTx(CWalletTx const&) <null> (bitcoind+0x57e0b1)
    #4 CWallet::AddToWallet(std::__1::shared_ptr<CTransaction const>, CWalletTx::Confirmation const&, std::__1::function<bool (CWalletTx&, bool)> const&, bool) <null> (bitcoind+0x535ec4)
    #5 CWallet::AddToWalletIfInvolvingMe(std::__1::shared_ptr<CTransaction const> const&, CWalletTx::Confirmation, bool) <null> (bitcoind+0x538114)
    #6 CWallet::ScanForWalletTransactions(uint256 const&, int, boost::optional<int>, WalletRescanReserver const&, bool) <null> (bitcoind+0x540262)
    #7 CWallet::RescanFromTime(long, WalletRescanReserver const&, bool) <null> (bitcoind+0x53f236)
    #8 RescanWallet(CWallet&, WalletRescanReserver const&, long, bool) <null> (bitcoind+0x5aa32e)
    #9 importprivkey(JSONRPCRequest const&) <null> (bitcoind+0x5a8ec5)
    #10 std::__1::__function::__func<CRPCCommand::CRPCCommand(char const*, char const*, UniValue (*)(JSONRPCRequest const&), std::initializer_list<char const*>)::'lambda'(JSONRPCRequest const&, UniValue&, bool), std::__1::allocator<CRPCCommand::CRPCCommand(char const*, char const*, UniValue (*)(JSONRPCRequest const&), std::initializer_list<char const*>)::'lambda'(JSONRPCRequest const&, UniValue&, bool)>, bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool&&) <null> (bitcoind+0x281bed)
    #11 std::__1::__function::__func<interfaces::(anonymous namespace)::WalletClientImpl::registerRpcs()::'lambda'(JSONRPCRequest const&, UniValue&, bool), std::__1::allocator<interfaces::(anonymous namespace)::WalletClientImpl::registerRpcs()::'lambda'(JSONRPCRequest const&, UniValue&, bool)>, bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool&&) <null> (bitcoind+0x43b86e)
    #12 std::__1::__function::__func<interfaces::(anonymous namespace)::RpcHandlerImpl::RpcHandlerImpl(CRPCCommand const&)::'lambda'(JSONRPCRequest const&, UniValue&, bool), std::__1::allocator<interfaces::(anonymous namespace)::RpcHandlerImpl::RpcHandlerImpl(CRPCCommand const&)::'lambda'(JSONRPCRequest const&, UniValue&, bool)>, bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool&&) <null> (bitcoind+0x147722)
    #13 CRPCTable::execute(JSONRPCRequest const&) const <null> (bitcoind+0x32aa16)
    #14 std::__1::__function::__func<StartHTTPRPC(util::Ref const&)::$_0, std::__1::allocator<StartHTTPRPC(util::Ref const&)::$_0>, bool (HTTPRequest*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(HTTPRequest*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) <null> (bitcoind+0x400d2a)
    #15 HTTPWorkItem::operator()() <null> (bitcoind+0x40b072)
    #16 WorkQueue<HTTPClosure>::Run() <null> (bitcoind+0x40d175)
    #17 HTTPWorkQueueRun(WorkQueue<HTTPClosure>*, int) <null> (bitcoind+0x40731c)
    #18 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(WorkQueue<HTTPClosure>*, int), WorkQueue<HTTPClosure>*, int> >(void*) <null> (bitcoind+0x40dc38)
  Mutex M132362 (0x7b5c00020030) created at:
    #0 pthread_mutex_init <null> (bitcoind+0x7172d)
    #1 std::__1::recursive_mutex::recursive_mutex() <null> (libc++.so.1+0x83583)
    #2 CWallet::CreateWalletFromFile(interfaces::Chain&, WalletLocation const&, bilingual_str&, std::__1::vector<bilingual_str, std::__1::allocator<bilingual_str> >&, unsigned long) <null> (bitcoind+0x527e5b)
    #3 CreateWallet(interfaces::Chain&, std::__1::basic_string<char, std::__1::char_traits<char>, secure_allocator<char> > const&, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bilingual_str&, std::__1::vector<bilingual_str, std::__1::allocator<bilingual_str> >&, std::__1::shared_ptr<CWallet>&) <null> (bitcoind+0x525d41)
    #4 createwallet(JSONRPCRequest const&) <null> (bitcoind+0x4a0267)
    #5 std::__1::__function::__func<CRPCCommand::CRPCCommand(char const*, char const*, UniValue (*)(JSONRPCRequest const&), std::initializer_list<char const*>)::'lambda'(JSONRPCRequest const&, UniValue&, bool), std::__1::allocator<CRPCCommand::CRPCCommand(char const*, char const*, UniValue (*)(JSONRPCRequest const&), std::initializer_list<char const*>)::'lambda'(JSONRPCRequest const&, UniValue&, bool)>, bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool&&) <null> (bitcoind+0x281bed)
    #6 std::__1::__function::__func<interfaces::(anonymous namespace)::WalletClientImpl::registerRpcs()::'lambda'(JSONRPCRequest const&, UniValue&, bool), std::__1::allocator<interfaces::(anonymous namespace)::WalletClientImpl::registerRpcs()::'lambda'(JSONRPCRequest const&, UniValue&, bool)>, bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool&&) <null> (bitcoind+0x43b86e)
    #7 std::__1::__function::__func<interfaces::(anonymous namespace)::RpcHandlerImpl::RpcHandlerImpl(CRPCCommand const&)::'lambda'(JSONRPCRequest const&, UniValue&, bool), std::__1::allocator<interfaces::(anonymous namespace)::RpcHandlerImpl::RpcHandlerImpl(CRPCCommand const&)::'lambda'(JSONRPCRequest const&, UniValue&, bool)>, bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool&&) <null> (bitcoind+0x147722)
    #8 CRPCTable::execute(JSONRPCRequest const&) const <null> (bitcoind+0x32aa16)
    #9 std::__1::__function::__func<StartHTTPRPC(util::Ref const&)::$_0, std::__1::allocator<StartHTTPRPC(util::Ref const&)::$_0>, bool (HTTPRequest*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(HTTPRequest*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) <null> (bitcoind+0x400d2a)
    #10 HTTPWorkItem::operator()() <null> (bitcoind+0x40b072)
    #11 WorkQueue<HTTPClosure>::Run() <null> (bitcoind+0x40d175)
    #12 HTTPWorkQueueRun(WorkQueue<HTTPClosure>*, int) <null> (bitcoind+0x40731c)
    #13 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(WorkQueue<HTTPClosure>*, int), WorkQueue<HTTPClosure>*, int> >(void*) <null> (bitcoind+0x40dc38)
  Mutex M132877 (0x7b5000010878) created at:
    #0 pthread_mutex_init <null> (bitcoind+0x7172d)
    #1 std::__1::recursive_mutex::recursive_mutex() <null> (libc++.so.1+0x83583)
    #2 CWallet::SetupLegacyScriptPubKeyMan() <null> (bitcoind+0x5556ae)
    #3 CWallet::CreateWalletFromFile(interfaces::Chain&, WalletLocation const&, bilingual_str&, std::__1::vector<bilingual_str, std::__1::allocator<bilingual_str> >&, unsigned long) <null> (bitcoind+0x528359)
    #4 CreateWallet(interfaces::Chain&, std::__1::basic_string<char, std::__1::char_traits<char>, secure_allocator<char> > const&, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bilingual_str&, std::__1::vector<bilingual_str, std::__1::allocator<bilingual_str> >&, std::__1::shared_ptr<CWallet>&) <null> (bitcoind+0x525d41)
    #5 createwallet(JSONRPCRequest const&) <null> (bitcoind+0x4a0267)
    #6 std::__1::__function::__func<CRPCCommand::CRPCCommand(char const*, char const*, UniValue (*)(JSONRPCRequest const&), std::initializer_list<char const*>)::'lambda'(JSONRPCRequest const&, UniValue&, bool), std::__1::allocator<CRPCCommand::CRPCCommand(char const*, char const*, UniValue (*)(JSONRPCRequest const&), std::initializer_list<char const*>)::'lambda'(JSONRPCRequest const&, UniValue&, bool)>, bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool&&) <null> (bitcoind+0x281bed)
    #7 std::__1::__function::__func<interfaces::(anonymous namespace)::WalletClientImpl::registerRpcs()::'lambda'(JSONRPCRequest const&, UniValue&, bool), std::__1::allocator<interfaces::(anonymous namespace)::WalletClientImpl::registerRpcs()::'lambda'(JSONRPCRequest const&, UniValue&, bool)>, bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool&&) <null> (bitcoind+0x43b86e)
    #8 std::__1::__function::__func<interfaces::(anonymous namespace)::RpcHandlerImpl::RpcHandlerImpl(CRPCCommand const&)::'lambda'(JSONRPCRequest const&, UniValue&, bool), std::__1::allocator<interfaces::(anonymous namespace)::RpcHandlerImpl::RpcHandlerImpl(CRPCCommand const&)::'lambda'(JSONRPCRequest const&, UniValue&, bool)>, bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool&&) <null> (bitcoind+0x147722)
    #9 CRPCTable::execute(JSONRPCRequest const&) const <null> (bitcoind+0x32aa16)
    #10 std::__1::__function::__func<StartHTTPRPC(util::Ref const&)::$_0, std::__1::allocator<StartHTTPRPC(util::Ref const&)::$_0>, bool (HTTPRequest*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(HTTPRequest*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) <null> (bitcoind+0x400d2a)
    #11 HTTPWorkItem::operator()() <null> (bitcoind+0x40b072)
    #12 WorkQueue<HTTPClosure>::Run() <null> (bitcoind+0x40d175)
    #13 HTTPWorkQueueRun(WorkQueue<HTTPClosure>*, int) <null> (bitcoind+0x40731c)
    #14 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(WorkQueue<HTTPClosure>*, int), WorkQueue<HTTPClosure>*, int> >(void*) <null> (bitcoind+0x40dc38)
  Thread T18 'b-httpworker.0' (tid=37580, running) created by main thread at:
    #0 pthread_create <null> (bitcoind+0x701ab)
    #1 std::__1::thread::thread<void (&)(WorkQueue<HTTPClosure>*, int), WorkQueue<HTTPClosure>*&, int&, void>(void (&)(WorkQueue<HTTPClosure>*, int), WorkQueue<HTTPClosure>*&, int&) <null> (bitcoind+0x40db10)
    #2 void std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread> >::__emplace_back_slow_path<void (&)(WorkQueue<HTTPClosure>*, int), WorkQueue<HTTPClosure>*&, int&>(void (&)(WorkQueue<HTTPClosure>*, int), WorkQueue<HTTPClosure>*&, int&) <null> (bitcoind+0x40d472)
    #3 StartHTTPServer() <null> (bitcoind+0x4070d8)
    #4 AppInitMain(util::Ref const&, NodeContext&) <null> (bitcoind+0x117751)
    #5 main <null> (bitcoind+0x10000c)
  Thread T16 'b-scheduler' (tid=37578, running) created by main thread at:
    #0 pthread_create <null> (bitcoind+0x701ab)
    #1 boost::thread::start_thread_noexcept() <null> (bitcoind+0x7a279d)
    #2 AppInitMain(util::Ref const&, NodeContext&) <null> (bitcoind+0x1171ee)
    #3 main <null> (bitcoind+0x10000c)
SUMMARY: ThreadSanitizer: data race (/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/bitcoind+0x79de7) in memmove
==================
```

</p>
</details>

**Comment by hebasto** [comment]
The issue is reproducible locally on Linux Mint 20 (x86_64).

**Comment by MarcoFalke** [comment]
In the meantime (before fixing the bug) a suppression can be added

**Comment by hebasto** [comment]
@MarcoFalke 
> In the meantime (before fixing the bug) a suppression can be added

Done in #19450.

**Comment by fanquake** [comment]
Does it makes sense to keep this open any longer given #20276?
Otherwise, what is there actual actionable todo here? Does the original problem still occur with master?
