### ISSUE TITLE
UI Hangs when running as std user

### ISSUE THREAD

**Issue by oguzhanf** [bitcoin/bitcoin#21136]
When accessing the Open Wallet from the File Menu, the UI hangs. Looking at the debug.log in the data directory, there are thousands of ListWalletDir: ACcess is Denied E:\$Recycle.bin\s-1-5-18 events. 

The data directory is set to be the root of a USB drive mapped to the E: letter. 

Client is started as std user. 

**Expected behavior**

Expected behaviour is for the client UI to handle the access issue and continue, possibly noting the requirement to have further permissions. Even when the client is started as administrator, the same hang occurs. It appears the client data directory should be set to a folder and not the root of a drive. 

**Actual behavior**

Any attempt to access the open wallet menu gets stuck. 

**To reproduce**

Install bitcoin core 0.21.0 x64
Set data directory to the root of a drive in Windows
Let sync or not, hover over the Open Wallet menu
Program UI hangs

**System information**

bitcoin core 0.21.0 x64

Windows 10 x64 PC, SSD drive, Core i9 9980xe

Windows 10 20H2 Build 19042.789

thousands of lines of the below. The debug.log is 370MB. 

05:32:18Z ListWalletDir: Access is denied E:\System Volume Information
2021-02-10T05:32:18Z ListWalletDir: Access is denied E:\System Volume Information
2021-02-10T05:32:18Z ListWalletDir: Access is denied E:\System Volume Information

**Comment by Saibato** [comment]
pls take a look at https://github.com/bitcoin/bitcoin/issues/20956
or  https://github.com/bitcoin/bitcoin/pull/19419
or https://github.com/bitcoin-core/gui/issues/16

btw; this is fixed in bitcoin knots afaik 
https://github.com/luke-jr/bitcoin/commit/d4e0e38d112cb6df0a15d348111e213466d9db14

**Comment by puchu** [comment]
Luks patch doesn't really solve the problem for me.

But the ui hangs got much worse in 0.21.0 and 0.21.1, when i compile 0.20.1 or 0.20.0, bitcoin-qt stays more responsive and only has sometimes (while syncing) 1-2 second hangs, with 0.21.* the lags raised dramatically, the interface hangs now up to 10-20 seconds (while syncing).

**Comment by puchu** [comment]
@luke-jr patch doesn't solve the problem for me. Maybe he has some input?

But the ui hangs got much worse in 0.21.0 and 0.21.1, when i compile 0.20.1 or 0.20.0, bitcoin-qt stays more responsive and only has sometimes (while syncing) 1-2 second hangs, with 0.21.* the lags raised dramatically, the interface hangs now up to 10-20 seconds (while syncing).

**Comment by puchu** [comment]
@luke-jr patch doesn't solve the problem for me. Maybe he has some input?

But the ui hangs got much worse in 0.21.0 and 0.21.1, when i compile 0.20.1 or 0.20.0, bitcoin-qt stays more responsive and only has sometimes (while syncing) 1-2 second hangs, with 0.21.* the lags raised dramatically, the interface hangs now up to 5-20 seconds (while syncing).

Ehat would be the best way to do a bisect, with the different branches?

**Comment by puchu** [comment]
@luke-jr patch doesn't solve the problem for me. Maybe he has some input?

But the ui hangs got much worse in 0.21.0 and 0.21.1, when i compile 0.20.1 or 0.20.0, bitcoin-qt stays more responsive and only has sometimes (while syncing) 1-2 second hangs, with 0.21.* the lags raised dramatically, the interface hangs now up to 5-20 seconds (while syncing).

What would be the best way to do a bisect, with the different branches?

**Comment by hebasto** [comment]
@oguzhanf @puchu 

Do you mind testing #21907?

**Comment by puchu** [comment]
i don't use windows
