### ISSUE TITLE
Sanitize fee rates  (user input)

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#21893]
It would be nice to sanitize fee rates from user input.

For example the block min fee rate is simply parsed as int64_t value. As fee rates are multiplied by the package size, this can easily lead to overflow.

```
    if (gArgs.IsArgSet("-blockmintxfee") && ParseMoney(gArgs.GetArg("-blockmintxfee", ""), n)) {
```

Assuming a maximum transaction size of at most 4MvB, this would give an upper bound for the fee rate of ~46116 BTC/kvB. Though, any fee rate larger than 1 BTC/kvB is probably nonsense and should be rejected early on startup.

**Comment by prayank23** [comment]
Concept ACK. Always good to sanitize user input.

**Comment by jonatack** [comment]
Yes. Sanitizing port numbers from user input is on my list as a follow-up to #21328, so if no one picks this up I might.

**Comment by amadeuszpawlik** [comment]
Would this be on the right track: https://github.com/amadeuszpawlik/bitcoin/commit/a0cedcf0ac701f2a3d01bd101f42e109aef806c9 ?

**Comment by aureleoules** [comment]
I believe this is fixed with #22220.

**Comment by MarcoFalke** [comment]
No, the integer overflow should still exists, see also https://github.com/bitcoin/bitcoin/pull/22044#issuecomment-878440985
