### ISSUE TITLE
wallet/spend.cpp assertion error

### ISSUE THREAD

**Issue by agent-ly** [bitcoin/bitcoin#26232]
Bitcoind fails to determine a fee rate which ends up crashing

RPC method `sentoaddress` should work as intended and properly calculate the fee.

It throws and error and exits bitcoind

```
2022-10-03T03:19:42Z FeeEst: 48 > 85% decay 0.99520: feerate: 1000 from (0 - 1000) 99.11% 3063.7/(3067.7 0 mem 23.6 out) Fail: (-1 - -1) 0.00% 0.0/(0.0 0 mem 0.0 out)
2022-10-03T03:19:42Z FeeEst: 12 > 85% decay 0.96200: feerate: 1000 from (0 - 1000) 97.41% 331.8/(340.6 0 mem 0.0 out) Fail: (-1 - -1) 0.00% 0.0/(0.0 0 mem 0.0 out)
2022-10-03T03:19:42Z FeeEst: 612 > 95% decay 0.99931: feerate: 1000 from (0 - 1000) 100.00% 9445.0/(9445.0 0 mem 0.0 out) Fail: (-1 - -1) 0.00% 0.0/(0.0 0 mem 0.0 out)
bitcoind: wallet/spend.cpp:783: bool CWallet::CreateTransactionInternal(const std::vector<CRecipient>&, CTransactionRef&, CAmount&, int&, bilingual_str&, const CCoinControl&, FeeCalculation&, bool): Assertion `coin_selection_params.m_subtract_fee_outputs || fee_needed <= change_and_fee - change_amount' failed.
Aborted (core dumped)
```

Can't reproduce, the error is seemingly random.

22.0

Windows 11 WSL Linux Ubuntu 20.04
Ryzen 9 5950X
64 GB RAM

**Comment by fanquake** [comment]
Looks like this might be the same as #23353, which should have been fixed by #22949. Are you able to test with 23.0, as we haven't yet released a 22.1.

**Comment by Jezz12-cloud** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue
https://direct.lc.chat/14571264/

**Comment by agent-ly** [comment]
> Looks like this might be the same as #23353, which should have been fixed by #22949. Are you able to test with 23.0, as we haven't yet released a 22.1.

I will test with 23.0 as setting s fallback fee rate did not solve the issue.

**Comment by live-suppo** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue
https://direct.lc.chat/14571264/

**Comment by fanquake** [comment]
> I will test with 23.0

@agent-ly were you able to test with 23.0?

**Comment by fanquake** [comment]
ping @agent-ly

**Comment by MarcoFalke** [comment]
Anything holding back a 22.1rc1?

**Comment by fanquake** [comment]
> Anything holding back a 22.1rc1?

#26430.
