### ISSUE TITLE
Rapidly getting blocks via RPC causes bitcoind to temporarily stop responding to RPC commands

### ISSUE THREAD

**Issue by ryanxcharles** [bitcoin/bitcoin#2889]
When retrieving blocks from the blockchain using bitcoind RPC commands, bitcoind will temporarily stop sending responses to RPC commands after many thousands of commands if the commands are sent in quick succession. The issue has something to do with timing, since adding a delay to retrieving blocks will make the problem go away.

This node.js code will display the issue (obviously, replace "password" with your bitcoind password):

```javascript
var rpc=require('json-rpc2');
var bitcoind=rpc.Client.create(8332, "localhost",
  "bitcoinrpc", "password");
var chain=function(blockhash){
  bitcoind.call('getblock',[blockhash],function(err,block){
    if (err){
      console.log(String(err));
      if (String(err)=="Error: Have no response object"){
        console.log("Thought so.");
      }
      return;
    }
    console.log(block.hash, block.height);
    if (block.nextblockhash){
      chain(block.nextblockhash);
    };
  });
};
chain("000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f");
```

Note that my development machine has an SSD, and so blocks are retrieved quickly by bitcoind - it may be necessary to use an SSD to reproduce the problem.

What this code does is to retrieve the genesis block, then get the next block, and the next block, and so on, until it has got all the blocks. Except at around 25,000 or so blocks in (different every time), it will quit when it encounters a "no response object" error. This error has nothing to do with node.js or json-rpc2 - it is a bitcoind error. This can be seen by running bitcoin commands from the command prompt, which result in a "couldn't connect to server" error, e.g.:

```
> bitcoind getblock 00000000722ecede1cc4edd52a7d416bdafd6528f630926b0021b41a6b57ba5d
error: couldn't connect to server
```

After a few seconds, bitcoind will begin responding to commads again. It doesn't crash. It just stops responding to commands for a short while.

By delaying repeated RPC commands, the above code can be fixed to run without freezing bitcoind (notice the 10ms setTimeout):

```javascript
var rpc=require('json-rpc2');
var bitcoind=rpc.Client.create(8332, "localhost",
  "bitcoinrpc", "password");
var chain=function(blockhash){
  bitcoind.call('getblock',[blockhash],function(err,block){
    if (err){
      console.log(String(err));
      if (String(err)=="Error: Have no response object"){
        console.log("Thought so.");
      }
      return;
    }
    console.log(block.hash, block.height);
    if (block.nextblockhash){
      setTimeout(function(){
        chain(block.nextblockhash);
      },10);
    };
  });
};
chain("000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f");
```

**Comment by shivaenigma** [comment]
This is hapenning on my server after every few weeks .  We have a getblock call to bitcoind for each blocks. After few block numbers bitcoind RPC hangs ( I have tried waiting for 30 min , but doesn't help, have to kill bitcoind and restart). Running bitcoind 0.10.2 .

Is this fixed ?
I can attempt to write a script to reproduce if this is not fixed yet... in the latest source

**Comment by laanwj** [comment]
No, it's not fixed, that's why this issue is still open. A script to reproduce it would be very useful.

**Comment by shivaenigma** [comment]
I am not sure if this is bcoz of some throtlling feature on bitcoin , but this is how to reproduce

```python
from bitcoinrpc.authproxy import AuthServiceProxy
import sys
import threading
import traceback
import time

number = 5
conn = [None] * number
while(True):
  for i in range(0, number):
    try:
      conn[i] = AuthServiceProxy(sys.argv[1])
      count = conn[i].getblockcount()
      raw_block=conn[i].getblock(conn[i].getblockhash(count))
      print "Got block %d"%(count)  
    except:
      traceback.print_exc()
      #Ignore and continue
```

Run the above script and then u can see the bitcoin-cli getinfo will stop responding.

**Comment by shivaenigma** [comment]
Basically on my server sometimes lots of these connections are going into CLOSE_WAIT state
```
python   6388 ubuntu   11u  IPv4 156823      0t0  TCP localhost:37917->localhost:8332 (ESTABLISHED)
python   6388 ubuntu   13u  IPv4 125106      0t0  TCP localhost:36759->localhost:8332 (CLOSE_WAIT)
python   6898 ubuntu   11u  IPv4 128729      0t0  TCP localhost:36958->localhost:8332 (ESTABLISHED)
```

When the number of these CLOSE_WAIT connections is becoming 5 ... rpc calls wont respond anymore and I have to restart my client

**Comment by mcelrath** [comment]
This is likely the same as #6454 and fixed by #5677

**Comment by winteraz** [comment]
This is not fixed. I'm running a bitcoin node (with large amount of ram (i.e. 64GB) and after several requests to get the unspent transactions the rpc service get stuck and stops to responds to new requests.

**Comment by MarcoFalke** [comment]
@winteraz This issue is about five years old and was closed two years ago. If you are certain that you are running into the same issue, please open a new one and reference (link to) this issue.

Also, make sure to include steps to reproduce and the version you are using.
