### ISSUE TITLE
build: RFC Coverage build type

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#31047]
Porting this issue from: https://github.com/hebasto/bitcoin/issues/341.

It's not clear if using our Coverage build type works with Clang, or not. In the linked thread there are simultaneous claims that it "works", but also that it does not work. It seems from the discussion that even using GCC with the Coverage build type is flaky.

There's been suggestions to add a Coverage mode for Clang: https://github.com/hebasto/bitcoin/pull/233, however adding a second way of doing things, when the current way may not work properly, and (likely?) currently isn't being used by anyone, doesn't seem like a good approach, and adds even more complication to the build system. Note that devs are already using Clang for coverage regardless of if it currently exists in the build system (cc @dergoegge, @marcofleon, @vasild).

If using Clangs native coverage mode is what is preferred/is "better", then it'd seem better for us to replace the current, more GCC focussed implementation, with one that is geared towards LLVM/Clang, if the idea is to provide something that works out-of-the-box, and is generally used by the developers working on the project.

**Comment by dergoegge** [comment]
I haven't tried after the transition to CMake but I always had trouble with the build in coverage build mode (e.g. `make cov`). Usually there was problem with path prefixes or a `lcov` version mismatch. The coverage reports themselves were always hard to read and I could not find any documentation on how to read them, for example:

![Screenshot from 2024-10-07 12-18-00](https://github.com/user-attachments/assets/16e4469b-542c-44be-b305-d26f6a6d2092)

How is branch coverage supposed to be interpreted from this?

I've switched all my coverage reports to using LLVM's native coverage tooling: https://clang.llvm.org/docs/SourceBasedCodeCoverage.html#id3. I don't use our build in command to produce coverage reports but I think it's a useful thing to have, so devs can easily produce their own coverage reports. I can recommend switching to LLVM's native coverage reporting, as that has been far less of a struggle in my experience.

**Comment by vasild** [comment]
For me it seems best to use each compiler's native workflow. That is: gcov+lcov if using GCC and the [source based coverage](https://github.com/hebasto/bitcoin/issues/341#issuecomment-2316704163) if using Clang.

Would be nice if that is integrated into the build system so it boils down to just `cmake --i-want-coverage`, but if not, then some good instructions in `doc/` would be fine as well.

**Comment by fanquake** [comment]
> For me it seems best to use each compiler's native workflow. 

Sure, anyone can still use whatever they like. However our build system doesn't need to (and shouldn't have to) handle all possible combinations of compiler + tooling. Providing a single convenience build type that is the same as what is used by the majority of the developers seems fine, however I don't think we need to natively support anything outside of that, given it's unlikely to be tested/used, or work properly, and just futher complicates our build system.

**Comment by vasild** [comment]
> our build system doesn't need to (and shouldn't have to) handle all possible combinations of compiler + tooling

It is just two:
1. gcc compiler + gcov/lcov and
2. clang compiler + llvm-cov (source based).

(I think it is a waste of time and we should ignore a third option where we try to use the gcov/lcov workflow with clang).

> Providing a single convenience build type that is the same as what is used by the majority of the developers seems fine

I do not object this, but then if only 1. or only 2. is supported then the coverage build should produce an error if the compiler is the other one.

**Comment by fanquake** [comment]
> It is just two:

It's not though, because `gcc compiler + gcov/lcov` already encompasses more than 1 thing. i.e supporting different versions of gcov/lcov across releases.

**Comment by marcofleon** [comment]
I don't have a strong preference for which one is supported by the build system. I happened to learn about [llvm-cov](https://clang.llvm.org/docs/SourceBasedCodeCoverage.html) before coming upon the [coverage](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#compiling-for-test-coverage) section in the docs, so that's what I've been using on both macOS and Linux. It's been working well for me so far.

**Comment by fanquake** [comment]
cc @maflcko. Do you have an opinion here?

**Comment by dergoegge** [comment]
> I liked the summary stats per folder produced by the current approach, but if others like other stuff better, I don't mind.

The LLVM approach also supports that:

![Screenshot from 2024-10-10 13-52-58](https://github.com/user-attachments/assets/c97d3071-c767-4390-99c1-095391ecf477)

**Comment by vasild** [comment]
> I liked the summary stats per folder produced by the current approach, but if others like other stuff better, I don't mind.

Maybe I misunderstand, but somehow the above implies that we have to commit to one and give up on the other method. But one can create gcc or clang coverages regardless of what is integrated into the cmake build system. That integration would be just a convenience and we could have no integration, or just gcc (the current `master`), or just clang or both gcc and clang.

**Comment by fanquake** [comment]
Apparently code coverage on oss-fuzz has been broken since CMake. See https://issues.oss-fuzz.com/issues/379122777. Full logs (https://oss-fuzz-build-logs.storage.googleapis.com/log-6b12c5ff-d6c4-441c-a10f-2dffff96e82c.txt):
```bash
Step #7: [0m[0;31merror: /workspace/out/libfuzzer-coverage-x86_64/src/bitcoin-core/build_fuzz/src/wallet/wallet/walletdb.h: No such file or directory
Step #7: [0m[0;31mwarning: The file '/src/bitcoin-core/build_fuzz/src/wallet/wallet/walletdb.h' isn't covered.
Step #7: [0m[0;31merror: /workspace/out/libfuzzer-coverage-x86_64/src/bitcoin-core/build_fuzz/src/wallet/wallet/rpc/wallet.cpp: No such file or directory
Step #7: [0m[0;31mwarning: The file '/src/bitcoin-core/build_fuzz/src/wallet/wallet/rpc/wallet.cpp' isn't covered.
Step #7: [0m[0;31merror: /workspace/out/libfuzzer-coverage-x86_64/src/bitcoin-core/build_fuzz/src/wallet/util/task_runner.h: No such file or directory
Step #7: [0m[0;31mwarning: The file '/src/bitcoin-core/build_fuzz/src/wallet/util/task_runner.h' isn't covered.
Step #7: [0mwarning: 60 functions have mismatched data
Step #7: [2024-11-17 06:58:59,574 DEBUG] Finished generating per-file code coverage summary.
Step #7: [2024-11-17 06:58:59,574 DEBUG] Generating file view html index file as: "/workspace/out/libfuzzer-coverage-x86_64/report/linux/file_view_index.html".
Step #7: Traceback (most recent call last):
Step #7:   File "/opt/code_coverage/coverage_utils.py", line 829, in <module>
Step #7:     sys.exit(Main())
Step #7:   File "/opt/code_coverage/coverage_utils.py", line 823, in Main
Step #7:     return _CmdPostProcess(args)
Step #7:   File "/opt/code_coverage/coverage_utils.py", line 780, in _CmdPostProcess
Step #7:     processor.PrepareHtmlReport()
Step #7:   File "/opt/code_coverage/coverage_utils.py", line 577, in PrepareHtmlReport
Step #7:     self.GenerateFileViewHtmlIndexFile(per_file_coverage_summary,
Step #7:   File "/opt/code_coverage/coverage_utils.py", line 450, in GenerateFileViewHtmlIndexFile
Step #7:     self.GetCoverageHtmlReportPathForFile(file_path),
Step #7:   File "/opt/code_coverage/coverage_utils.py", line 422, in GetCoverageHtmlReportPathForFile
Step #7:     assert os.path.isfile(
Step #7: AssertionError: "/src/bitcoin-core/build_fuzz/crc32c/include/crc32c/crc32c.h" is not a file.
Step #7: ********************************************************************************
Step #7: Code coverage report generation failed.
Step #7: To reproduce, run:
Step #7: python infra/helper.py build_image bitcoin-core
Step #7: python infra/helper.py build_fuzzers --sanitizer coverage bitcoin-core
Step #7: python infra/helper.py coverage bitcoin-core
Step #7: ********************************************************************************
Finished Step #7
ERROR
```

**Comment by glozow** [comment]
@hebasto @theuni can you open a PR to prune the gcc stuff for v29?

**Comment by theuni** [comment]
Will do.

**Comment by theuni** [comment]
Hmm, I now see that @maflcko is still using the gcc coverage, so nuking it would break https://maflcko.github.io/b-c-cov/ .

@maflcko since you weren't on today's v29 milestone call: the consensus was to nuke the current gcc coverage support for v29 since it's "not working", and try to get llvm support in in its place, but that part wouldn't be a v29 release blocker.

But apparently it's working enough for you so I suspect you'd disagree with that?

**Comment by fanquake** [comment]
> to list the stuff I noticed that is using GCC coverage:

The only thing mentioned here is corecheck. Is there anything else (other than your use)?

> Figure out what the coverage workflow should look like. "Should there be gcc support at all?"

If we are currently unsure what our coverage support should even look like, I'm not sure we should ship something just because it exists, maybe just to delete it in the next release; that's why it's attached to a milestone. It seems reasonable to come to some sort of conslusion now.

Can you elaborate on "all the GCC/lcov/gcov problems" you mentioned here: https://github.com/bitcoin/bitcoin/pull/31588#issuecomment-2648315209? Seems like there is also some [agreement there](https://github.com/bitcoin/bitcoin/pull/31588#issuecomment-2651994364) to switch to LLVM/Clang.

**Comment by vasild** [comment]
I tried the coverage instructions from `doc/developer-notes.md` and gcc/gcov generated a reasonable report. It does not look broken. No reason to remove a working, documented and used feature, with urgency, in 29.

**Comment by maflcko** [comment]
> Can you elaborate on "all the GCC/lcov/gcov problems" you mentioned here: [#31588 (comment)](https://github.com/bitcoin/bitcoin/pull/31588#issuecomment-2648315209)? Seems like there is also some [agreement there](https://github.com/bitcoin/bitcoin/pull/31588#issuecomment-2651994364) to switch to LLVM/Clang.

I don't use macOS, nor have I tested this specific bash script on the different Linux distros mentioned, so I can't vouch for the problems, but it looks like some people ran into problems and shared them in the thread. In any case that specific script seems to be a dev-only test-only contrib script with 0(?) users right now, where at least the suppression list is stale. So I removed it from the milestone in https://github.com/bitcoin/bitcoin/pull/31588#issuecomment-2652009268. I'll follow-up with my follow-up, but earliest I can do is next week or later.

> I'm not sure we should ship something just because it exists, maybe just to delete it in the next release; that's why it's attached to a milestone.

It not only exists, but it is also used. For example:

* [corecheck](https://github.com/corecheck/corecheck/blob/7734c3773da2ae2f133b7a720dee7d3ede966520/workers/coverage-worker/entrypoint.sh#L50), https://github.com/corecheck/corecheck/issues/96
* https://maflcko.github.io/b-c-cov/
* https://github.com/maflcko/DrahtBot/blob/1cce096df7cb4d89d34bcdbed09b20a38fe2a344/coverage_fuzz/src/main.rs#L40 (used for qa-asset commits (see that repo), or bitcoin core commits: https://github.com/bitcoin/bitcoin/pull/31841#issuecomment-2656491879)
* https://github.com/maflcko/DrahtBot/blob/1cce096df7cb4d89d34bcdbed09b20a38fe2a344/coverage/src/main.rs#L40 (not used recently, but can be used on any bitcoin core commit post cmake)

If those use cases are considered invalid, then removing it seems fine. However, if others think that those are useful use-cases, then my recommendation would be to first update them and then remove the feature.

If there are any risks or downsides in removing the milestone from this issue, it would help to list them. If it is just a documentation problem that the "feature" will be removed, it should be trivial to fix:

`sed -i 's/Coverage/DangerCoverageExperimentalWillBeRemoved/g' ...`

**Comment by fanquake** [comment]
Looking at Corecheck, does it use our `Coverage.cmake`? I can't find it being used anywhere there, seems like only calls to gcovr directly.

**Comment by maflcko** [comment]
Can this be closed as fixed by [31933](https://github.com/bitcoin/bitcoin/pull/31933)?

**Comment by fanquake** [comment]
I don't think so. If anything, it's even more of an indication that we should swap what has been implemented for GCC (and still not documented as such, leading to i.e #32571) for LLVM / Clang, which is clearly what (the majority of) project contributors are using, or wanting to use.

**Comment by vasild** [comment]
My impression is that a non-trivial part of the developers use Linux with its native compiler GCC. The current GCC-oriented method we have [does work](https://github.com/bitcoin/bitcoin/issues/31047#issuecomment-2658930755) with GCC, contrary to what the OP suggests "the current way may not work properly".

So, to me it looks like that removing the current GCC-oriented way could affect some developers in a negative way. I could be wrong though. Maybe none of the Linux people generate code coverage? 👀  Or they bother to install Clang additionally and use that?

Lets see if a quick poll on IRC would help bring some clarity to this: https://www.erisian.com.au/bitcoin-core-dev/log-2025-06-12.html#l-69

**Comment by vasild** [comment]
If the people that attended the [IRC meeting](https://www.erisian.com.au/bitcoin-core-dev/log-2025-06-12.html#l-362) is a representative sample, then I guess it might be ok to ditch the current GCC-oriented coverage "integration" into CMake and replace it with Clang's (which is already documented at `doc/developer-notes.md` / `Using LLVM/Clang toolchain`), instead of having to maintain both.

I guess there will be more feedback once there is a PR which does that.

**Comment by maflcko** [comment]
> I guess there will be more feedback once there is a PR which does that.

There already is (well not a replacement, but close enough), see https://github.com/bitcoin/bitcoin/pull/31394#issuecomment-2809965643

**Comment by nkaretnikov** [comment]
I tried getting lcov working using `Coverage.cmake` yesterday on de925455c8 and I couldn't get it to work.
Both gcc and clang built the project fine, but the lcov step was generating errors.

<details>
<summary>shell.nix env</summary>

gcc is implicitly part of this environment, so I didn't need to add it.
The exported vars should not be a problem because I explicitly set compilers later.

```nix
with import <nixpkgs> {};

mkShell {
  packages = [
    cmake
    llvmPackages_latest.clang
    llvmPackages_latest.lld
    llvmPackages_latest.llvm
    sqlite
    capnproto
    boost
    pkg-config
    libevent
    python3
    lcov
  ];

  shellHook = ''
    export CC=clang
    export CXX=clang++
  '';
}
```
</details>

<details>
<summary>gcc/clang + lcov</summary>
The build for clang was similar, you just need to adjust the C/CXX compiler variables, but I wouldn't expect it to work with lcov if gcc doesn't, so I'm including the gcc version.

```Makefile
.PHONY: clean build shell test cov

NUM_JOBS=1

# To run:
# nix-shell --pure --run 'make clean build && exec $SHELL'

shell:
	nix-shell --pure

# https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#using-lcov
build:
	cmake -B build \
		-DCMAKE_BUILD_TYPE=Coverage \
		-DCMAKE_C_COMPILER=gcc \
		-DCMAKE_CXX_COMPILER=g++
	cmake --build build -j ${NUM_JOBS}

test:
	cmake -DJOBS="${NUM_JOBS}" -P build/Coverage.cmake
	@printf '%s\n' "Coverage report: build/total.coverage/index.html"

clean:
	rm -rf build
```

</details>


<details>
<summary>clang + llvm-cov</summary>

```Makefile
.PHONY: clean build shell test cov

NUM_JOBS=1

# To run:
# nix-shell --pure --run 'make clean build && exec $SHELL'

shell:
	nix-shell --pure

# https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#using-llvmclang-toolchain
build:
	cmake -B build -DCMAKE_C_COMPILER="clang" \
	-DCMAKE_CXX_COMPILER="clang++" \
	-DAPPEND_CFLAGS="-fprofile-instr-generate -fcoverage-mapping" \
	-DAPPEND_CXXFLAGS="-fprofile-instr-generate -fcoverage-mapping" \
	-DAPPEND_LDFLAGS="-fprofile-instr-generate -fcoverage-mapping"
	cmake --build build -j ${NUM_JOBS}

test:
	mkdir -p build/raw_profile_data
	LLVM_PROFILE_FILE="${CURDIR}/build/raw_profile_data/%m_%p.profraw" ctest --test-dir build -j ${NUM_JOBS}
	LLVM_PROFILE_FILE="${CURDIR}/build/raw_profile_data/%m_%p.profraw" build/test/functional/test_runner.py -j ${NUM_JOBS}
	find build/raw_profile_data -name "*.profraw" > build/raw_profile_data_files.txt
	llvm-profdata merge -f build/raw_profile_data_files.txt -o build/coverage.profdata

cov:
	llvm-cov show \
	    --object=build/bin/test_bitcoin \
	    --object=build/bin/bitcoind \
	    -Xdemangler=llvm-cxxfilt \
	    --instr-profile=build/coverage.profdata \
	    --ignore-filename-regex="src/crc32c/|src/leveldb/|src/minisketch/|src/secp256k1/|src/test/" \
	    --format=html \
	    --show-instantiation-summary \
	    --show-line-counts-or-regions \
	    --show-expansions \
	    --output-dir=build/coverage_report \
	    --project-title="Bitcoin Core Coverage Report"

clean:
	rm -rf build
```
</details>

Based on this experience, I recommend switching to clang + llvm-cov in `Coverage.cmake`. This configuration also has an advantage since clang and coverage are often used in fuzzing, with libFuzzer and sanitizers.

**Comment by maflcko** [comment]
Not sure what the current status here is. Looks like there was an IRC meeting that concluded it would be fine to remove the GCC coverage cmake type. Given that there are docs for llmv, it seems fine to fully remove it without replacement, but some places need to be updated first, see https://github.com/bitcoin/bitcoin/issues/31047#issuecomment-2658944005 for a list.

**Comment by maflcko** [comment]
Only slightly related: Both gcov and llvm-cov seem  filled with bugs, see the thread in https://github.com/bitcoin-core/qa-assets/pull/292 listing a few bugs.
