### ISSUE TITLE
Linux download needs installation instructions

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#32097]
Windows has an installer, macOS has the usual drag-me-to-finder logic that most GUI users will be familiar with. But for Linux we just give people are bunch of binaries and a README without any installation instructions.

Worse, it turns out the binaries don't work out of the box on a vanilla Ubuntu system. That's not just because of Wayland, which we don't support yet. Even on X it will miss certain libraries.

https://www.reddit.com/r/BitcoinBeginners/comments/14m8f9q/missing_required_library_to_run_core_on_ubuntu/

The easiest fix would be to point to https://bitcoin.org/en/full-node#other-linux-gui which at least gives some general instructions.

Better I think would be to add instructions for the most popular desktop distros.

I think it's fine to assume that daemon users can figure it out for themselves.

**Comment by hodlinator** [comment]
> https://bitcoin.stackexchange.com/questions/122646/libxcb-xinerama0-library-required-by-bitcoin-qt

(This seems to have led to #30061 with the same title).

**Comment by Sjors** [comment]
That's a useful reference. But the concern there is about security, depending on operating system libraries. Here I'm just worried about the practically of installing. As linux desktop gets more user friendly, I expect fewer people to know how to figure out which libraries they're missing and how to install them.

**Comment by maflcko** [comment]
I think this was fixed and can be closed?

**Comment by fanquake** [comment]
Yea I'm not sure. For master, the binaries still have a `libxcb-cursor` dependency, that may need to be installed. It's not clear if #33238 will work for `29.x`, so that will still have a `libxcb-xinerama` dependency, that may need to be installed, (same for `28.x`). There's a note about `libxcb-cursor0` in build-unix, but that isn't shipped with release binaries, or likely read by anyone who isn't compiling from source, so it seems like any of this could benefit from additional documentation.

Thoughts @hebasto?

**Comment by maflcko** [comment]
> There's a note about `libxcb-cursor0` in build-unix, but that isn't shipped with release binaries, or likely read by anyone who isn't compiling from source, so it seems like any of this could benefit from additional documentation.

I see, so it seems a bit related to https://github.com/bitcoin/bitcoin/issues/32565

**Comment by fanquake** [comment]
Added this to `30.0`, but this seems to need addressing for all release branches, in some way.

**Comment by BenWestgate** [comment]
If we added to the tarball:
```
./share/applications/bitcoin-qt.desktop
./share/icons/bitcoin128.png
./share/mime/packages/x-scheme-handler-bitcoin.xml
./share/doc/bitcoin-core/README.md
./share/doc/bitcoin-core/bitcoin.conf
```
Then a local install can be performed by:
`tar xzf bitcoin-29.1-x86_64-linux-gnu.tar.gz --strip-components=1 --directory=$HOME/.local`
and a system wide install by:
`sudo tar xzf bitcoin-29.1-x86_64-linux-gnu.tar.gz --strip-components=1 --directory=/usr/local`

We currently have two files in `./`: `README.md` and `bitcoin.conf` which are in the wrong place for [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/) that must be moved to enable the one line install.

`bitcoin.conf` either belongs in `./share/doc/bitcoin-core/` as documentation or perhaps more preferably generated at start-up and placed in the data_dir (default: `~/.bitcoin`) similar to many other files.

**Comment by fanquake** [comment]
@hebasto can you followup here

**Comment by fanquake** [comment]
See #33432. 
> Doing sudo apt install libxcb-cursor0 seems to have fixed the issue

**Comment by hebasto** [comment]
> [@hebasto](https://github.com/hebasto) can you followup here

https://github.com/bitcoin/bitcoin/pull/33451.
