### ISSUE TITLE
[OSX] 0.10.0 rc3 osx probably has issues with special chars

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#5657]
Focus on the balance value fields.

![bildschirmfoto 2015-01-14 um 09 18 15](https://cloud.githubusercontent.com/assets/178464/5735883/47c5f142-9bce-11e4-8825-5fce35192a27.png)

**Comment by jonasschnelli** [comment]
maybe related to https://github.com/bitcoin/bitcoin/issues/5165

**Comment by jonasschnelli** [comment]
on osx 10.7 and 10.9 it looks okay:

![bildschirmfoto 2015-01-14 um 10 00 44](https://cloud.githubusercontent.com/assets/178464/5736282/5a35abf0-9bd4-11e4-8506-3f11be4c15a8.png)

**Comment by theuni** [comment]
We've tracked this issue down to the sdk used to build qt. When built with >= 10.8 sdk, qt uses new apis to discover fonts, rather than the old unreliable methods. For master, we should bump up to a newer SDK. For 0.10, we have a few options.

Some background info on SDKs: https://github.com/bitcoin/bitcoin/pull/5582#issuecomment-68463725

Options:
- Remove the thin-space stuff for 0.10, possibly only for osx 10.10. That wouldn't address #5165.
- Build 0.10 against 10.8
- Track down the font loading failure and attempt to insert a work-around like 292cc072f3bada256bc6af9970512eb9dec8d93a

I'd prefer to do the last one, if it's possible. Looking into it now.

**Comment by theuni** [comment]
I've pushed up a possible fix for 0.10, but I'm unable to test: https://github.com/theuni/bitcoin/commit/5175db6a19cddbcce874d27a58567e34932223aa

A binary is here: http://bitcoincore.org/cfields/bitcoin-qt-quickfix-e0cd2f55

**Comment by gavinandresen** [comment]
Tested on OSX 10.10.1, does NOT fix the problem (boxes instead of thin spaces if I set display to uBTC).

**Comment by jonasschnelli** [comment]
As reported on IRC (http://bitcoinstats.com/irc/bitcoin-dev/logs/2015/01/14#l1421271863) same issue on my osx 10.10 Retina with `bitcoin-qt-quickfix-e0cd2f55`

> Build 0.10 against 10.8

I was always a friend of dropping old os version from the support matrix. 10.8 was released in Feb 2012. 10.7 in Juli 2011.
But i assume others wish better backward compatibility and dropping 10.7 will probably make people whine about it.

**Comment by laanwj** [comment]
I'm not a fan of dropping support for a four year old OS just for a cosmetic glitch. But a shorter support cycle is inevitable if they wildly change the API every release. The extra work for supporting a certain release quickly outweighs the gain. Win32 os full of holes otherwise but at least extremely backwards compatible.

But for 0.10 it's too late to change supported OSes. Could bump the minimum to 10.8 for 0.11.

Can we package a fallback font in the OSX dmg?

**Comment by jonasschnelli** [comment]
related: https://bugzilla.mozilla.org/show_bug.cgi?id=931040
and: https://bugreports.qt.io/browse/QTBUG-40833

**Comment by jonasschnelli** [comment]
@theuni:
didn't went deep on that. But i saw you did gave a font substitute for the internal "special" OS font: `QFont::insertSubstitution(".Helvetica Neue DeskInterface", "Helvetica Neue");`
After a quick research i came to the point that this special . font your substituting could have a different font map. I saw that others create replacement for this .OS font (https://github.com/jenskutilek/FiraSystemFontReplacement). Maybe the substitute for this font should also be in the same format?

**Comment by jonasschnelli** [comment]
sry. wrong button

**Comment by theuni** [comment]
@laanwj That build was just a test to see where the floor for fixed builds was. @jonasschnelli also confirmed that the build against 10.8 with 10.6 back-compat worked: http://bitcoincore.org/cfields/bitcoin-qt-10.8_10.6_sdk-e0cd2f55 . @gavinandresen Could could you verify?

I'd rather not bump to using the 10.8 sdk for 0.10 now that the build process is settled, but I'm not sure what choice we have if it fixes #5165 as well.

@laanwj Looking into shipping the fonts. I suppose I'll go ahead and upgrade to 10.10 in order to test, seems that's the major trouble-case these days.

**Comment by gavinandresen** [comment]
e0cd2f55 fixes the issue for me on OSX 10.10.1.

**Comment by theuni** [comment]
@gavinandresen hmm? I'm not seeing the connection.
