### ISSUE TITLE
Prevent fee overpayment when nFeeNeeded decreases in CreateTransaction iterations

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#9466]
When a pass of CreateTransaction fails to select enough bitcoin to meet the nFeeNeeded the next pass through may select a far smaller collection of inputs.  Currently it will continue to use the old fee amount based on the larger set of inputs, which can cause a non-trivial over-payment.

This may be the cause of the behavior reported here: https://www.reddit.com/r/Bitcoin/comments/5ltw5n/bitcoin_core_v0131_sends_enormously_high_fee/

Long ago fixing this was tricky due to a catch-22 between signing the transaction and knowing how much fee was required.  But after #9465 the whole algorithm will run using a dummy signature, so when there is already a change output fixing up the fee after finding a sufficient transaction should be a matter of a ~2 line change.

**Comment by gmaxwell** [comment]
This is fixed by #9404.

**Comment by morcos** [comment]
@gmaxwell to be clear it's not completely fixed...  it's just much less likely to happen.

**Comment by RHavar** [comment]
Oh nice find! When I was going through my transactions, I noticed that occasionally it was paying absolutely ridiculous fee rates. I had assumed it was a problem with the fee estimation, but I'm guessing I was hit by this.
